export interface Platform {
  id: string;
  name: string;
  nameKifuliiru: string;
  url: string;
  description: string;
  descriptionKifuliiru: string;
  detailedDescription?: string;
  detailedDescriptionKifuliiru?: string;
  features?: string[];
  featuresKifuliiru?: string[];
  useCases?: string[];
  useCasesKifuliiru?: string[];
  benefits?: string[];
  benefitsKifuliiru?: string[];
  additionalInfo?: string;
  additionalInfoKifuliiru?: string;
}

export const platforms: Platform[] = [
  {
    id: 'kifuliiru-lab',
    name: 'Kifuliiru Lab',
    nameKifuliiru: 'Kifuliiru Lab',
    url: 'https://kifuliiru.org',
    description: 'The main platform for Kifuliiru language resources and tools.',
    descriptionKifuliiru: 'Mukolwa mukulu wa Kifuliiru Language Platform. Iliri hano higulu lyo kubona abandu bitu na ngisi gundi yeshi uwangasima ukumenya bikingi ku ndeto yitu Kifuliiru.',
    detailedDescription: 'Kifuliiru Lab is the main platform for Kifuliiru language resources and tools. It serves as the central hub for all Kifuliiru language initiatives and provides access to various learning resources, tools, and community features. The platform brings together researchers, educators, learners, and community members to collaborate on preserving and promoting the Kifuliiru language.',
    detailedDescriptionKifuliiru: 'Kifuliiru Lab iliri mukolwa mukulu wa Kifuliiru Language Platform. Iliri hano higulu lyo kubona abandu bitu na ngisi gundi yeshi uwangasima ukumenya bikingi ku ndeto yitu Kifuliiru. Ikugwasa tumenye bingi ku mikolwa yitu yoshi. Mukolwa guno gutunga abandu bingi: abakora, abasomesa, abasoma, na abandu ba kumanya kugwasa tumenye bingi ku ndeto yitu Kifuliiru.',
    features: [
      'Central hub for Kifuliiru resources',
      'Research and development tools',
      'Community collaboration platform',
      'Language preservation initiatives',
      'Educational resources',
      'Open source projects',
      'API access for developers',
    ],
    featuresKifuliiru: [
      'Mukolwa mukulu wa mikolwa ya Kifuliiru',
      'Mikolwa ya kukora na kumenya',
      'Mukolwa wa kugwasa abandu',
      'Mikolwa ya kudeta kwo ndeto',
      'Mikolwa ya kuyigiriza',
      'Mikolwa ya mahala',
      'API ya abakora',
    ],
    useCases: [
      'Language researchers studying Kifuliiru',
      'Developers building Kifuliiru language tools',
      'Educators creating learning materials',
      'Community members preserving culture',
      'Students learning the language',
    ],
    useCasesKifuliiru: [
      'Abakora abasoma Kifuliiru',
      'Abakora abakola mikolwa ya Kifuliiru',
      'Abasomesa abakola ibitaabo',
      'Abandu ba kumanya badeta kwo ndeto',
      'Abasoma abayigiriza ndeto',
    ],
    benefits: [
      'Access to comprehensive language resources',
      'Collaboration with language experts',
      'Open source tools and APIs',
      'Community support and engagement',
      'Research opportunities',
    ],
    benefitsKifuliiru: [
      'Kubona mikolwa yoshi ya ndeto',
      'Kugwasa abandu ba kumanya',
      'Mikolwa ya mahala na API',
      'Kugwasa abandu ba kumanya',
      'Nzaliro za kukora',
    ],
    additionalInfo: 'Kifuliiru Lab is committed to open source principles and community-driven development. All resources are freely available to support the preservation and growth of the Kifuliiru language.',
    additionalInfoKifuliiru: 'Kifuliiru Lab ikusima mikolwa ya mahala na kukola na abandu. Mikolwa yoshi iliri mahala higulu lyo kudeta kwo ndeto yitu Kifuliiru.',
  },
  {
    id: 'kifuliiru-com',
    name: 'Kifuliiru.com',
    nameKifuliiru: 'Kifuliiru.com',
    url: 'https://www.kifuliiru.com',
    description: 'The main website for Kifuliiru language learning and resources. Includes dictionary, verbs, proverbs, numbers, books, audio, and more.',
    descriptionKifuliiru: 'Mukolwa mukulu wa Kifuliiru Language Platform. Iliri hano higulu lyo kubona abandu bitu na ngisi gundi yeshi uwangasima ukumenya bikingi ku ndeto yitu Kifuliiru. Ikugwasa tumenye bingi ku amagambo, imikolwa, imigani, ukuharura, ibitaabo, amajwi, na bindi bingi.',
    detailedDescription: 'Kifuliiru.com is the comprehensive website for Kifuliiru language learning and resources. It includes a dictionary, verb conjugations, proverbs, number guides, books, audio content, and many other learning tools. This is the main hub for all Kifuliiru language resources. The platform offers interactive learning experiences, cultural content, and comprehensive language tools designed for learners at all levels, from complete beginners to advanced speakers.',
    detailedDescriptionKifuliiru: 'Kifuliiru.com iliri mukolwa mukulu wa Kifuliiru Language Platform. Iliri hano higulu lyo kubona abandu bitu na ngisi gundi yeshi uwangasima ukumenya bikingi ku ndeto yitu Kifuliiru. Ikugwasa tumenye bingi ku amagambo, imikolwa, imigani, ukuharura, ibitaabo, amajwi, na bindi bingi. Mukolwa guno gutunga mikolwa yingi ya kuyigiriza, ibindu bya kumenya, na mikolwa yoshi ya ndeto higulu lyo kubona abasoma byoshi, kuguma na abandu abayiji ndeto.',
    features: [
      'Comprehensive dictionary with translations',
      'Complete verb conjugation system',
      'Extensive proverbs collection',
      'Detailed number guides (0-999,999+)',
      'Digital books library',
      'Audio content hub',
      'Interactive language learning tools',
      'Cultural content and stories',
      'Multi-language support (ENG/FRN/SWA)',
      'Search functionality',
      'Mobile-friendly interface',
      'Regular content updates',
    ],
    featuresKifuliiru: [
      'Amagambo yoshi na kuyihindura',
      'Imikolwa yoshi',
      'Imigani yingi',
      'Ukuharura (0-999,999+)',
      'Ibitabo bya digital',
      'Mukolwa wa amajwi',
      'Mikolwa ya kuyigiriza',
      'Ibindu bya kumenya na imigani',
      'Zindi ndeto zingi (ENG/FRN/SWA)',
      'Kuharura',
      'Mukolwa wa telefoni',
      'Kugwasa ibindu bishasha',
    ],
    useCases: [
      'Daily vocabulary learning',
      'Grammar and verb conjugation practice',
      'Cultural immersion through stories',
      'Number system mastery',
      'Pronunciation practice with audio',
      'Reading comprehension exercises',
      'Cultural knowledge acquisition',
    ],
    useCasesKifuliiru: [
      'Kusoma amagambo kwa munsi',
      'Kuyigiriza imikolwa na grammar',
      'Kumenya kumenya mu imigani',
      'Kumenya ukuharura',
      'Kuyigiriza pronunciation na amajwi',
      'Kusoma na kumenya',
      'Kumenya ibindu bya kumenya',
    ],
    benefits: [
      'All-in-one learning platform',
      'Free access to all resources',
      'Suitable for all skill levels',
      'Regular content updates',
      'Community-driven content',
      'Mobile accessibility',
      'Multilingual support',
    ],
    benefitsKifuliiru: [
      'Mukolwa umwe wa kuyigiriza',
      'Kubona mikolwa yoshi mahala',
      'Higulu lyo abasoma byoshi',
      'Kugwasa ibindu bishasha',
      'Ibindu bya abandu ba kumanya',
      'Kubona na telefoni',
      'Zindi ndeto zingi',
    ],
    additionalInfo: 'Kifuliiru.com is continuously updated with new content, features, and improvements based on community feedback. The platform is designed to grow with the needs of learners and to preserve the rich cultural heritage embedded in the Kifuliiru language.',
    additionalInfoKifuliiru: 'Kifuliiru.com ikugwasa ibindu bishasha, mikolwa mishasha, na kumenya bweneene higulu lyo abandu ba kumanya. Mukolwa guno gutunga higulu lyo kugwasa abasoma na kudeta kwo kumenya kwa ndeto yitu Kifuliiru.',
  },
  {
    id: 'kifuliiru-dictionary',
    name: 'Kifuliiru Dictionary',
    nameKifuliiru: 'Kifuliiru Dictionary',
    url: 'https://dictionary.kifuliiru.net/',
    description: 'Kifuliiru Public Dictionary - Search for words in Kifuliiru and translate to English, French, and Swahili. Includes verbs, proverbs, and numbers.',
    descriptionKifuliiru: 'Mukolwa wa amagambo ge\'Kifuliiru. Iliri hano higulu lyo kubona amagambo ge\'Kifuliiru na kuyihindura mu zindi ndeto nga English, Français, na Kiswahili. Ikugwasa tumenye bingi ku amagambo, imikolwa, imigani, na ukuharura.',
    detailedDescription: 'The Kifuliiru Public Dictionary is a comprehensive dictionary that allows you to search for words in Kifuliiru and translate them to English, French, and Swahili. It includes extensive word lists, verb conjugations, proverbs, and number translations. Perfect for learners at all levels. The dictionary features a user-friendly interface, advanced search capabilities, and regularly updated content. It serves as an essential reference tool for anyone learning or using the Kifuliiru language.',
    detailedDescriptionKifuliiru: 'Kifuliiru Dictionary iliri mukolwa wa amagambo ge\'Kifuliiru. Iliri hano higulu lyo kubona amagambo ge\'Kifuliiru na kuyihindura mu zindi ndeto nga English, Français, na Kiswahili. Ikugwasa tumenye bingi ku amagambo, imikolwa, imigani, na ukuharura. Mukolwa guno gutunga mukolwa mwiza wa kubona amagambo, kuharura bweneene, na kugwasa ibindu bishasha. Iliri mukolwa muhamu higulu lyo abasoma na abandu abakoresha ndeto yitu Kifuliiru.',
    features: [
      'Advanced word search in Kifuliiru',
      'Multi-language translations (English, French, Swahili)',
      'Complete verb conjugation tables',
      'Extensive proverbs collection with meanings',
      'Comprehensive number translations',
      'Word of the day feature',
      'Recent additions tracking',
      'Alphabetical browsing (A-Z)',
      'Category filtering',
      'Pronunciation guides',
      'Example sentences',
      'Related words suggestions',
    ],
    featuresKifuliiru: [
      'Kuharura amagambo bweneene mu Kifuliiru',
      'Kuyihindura mu zindi ndeto zingi (English, Français, Kiswahili)',
      'Imikolwa yoshi',
      'Imigani yingi na kumenya',
      'Ukuharura yoshi',
      'Ijambo rya munsi',
      'Amagambo mashasha',
      'Kuharura na herufi (A-Z)',
      'Kuharura na kumanya',
      'Kumenya pronunciation',
      'Amagambo ya kumanya',
      'Amagambo yahamanye',
    ],
    useCases: [
      'Quick word lookups while reading',
      'Learning new vocabulary',
      'Understanding verb forms',
      'Exploring cultural proverbs',
      'Translating between languages',
      'Studying number systems',
      'Improving pronunciation',
    ],
    useCasesKifuliiru: [
      'Kubona amagambo mu kusoma',
      'Kusoma amagambo mashasha',
      'Kumenya imikolwa',
      'Kumenya imigani ya kumenya',
      'Kuyihindura mu zindi ndeto',
      'Kusoma ukuharura',
      'Kumenya pronunciation',
    ],
    benefits: [
      'Fast and accurate translations',
      'Free access to all features',
      'Regularly updated content',
      'Multiple language support',
      'User-friendly interface',
      'Mobile responsive design',
      'Community contributions welcome',
    ],
    benefitsKifuliiru: [
      'Kuyihindura bweneene na vuba',
      'Kubona mikolwa yoshi mahala',
      'Kugwasa ibindu bishasha',
      'Zindi ndeto zingi',
      'Mukolwa mwiza',
      'Mukolwa wa telefoni',
      'Abandu ba kumanya bakwiri kugwasa',
    ],
    additionalInfo: 'The Kifuliiru Dictionary is a community-driven project that welcomes contributions from native speakers and language experts. New words, corrections, and improvements are added regularly to ensure accuracy and completeness.',
    additionalInfoKifuliiru: 'Kifuliiru Dictionary iliri mukolwa wa abandu ba kumanya. Abandu abayiji ndeto yitu na abandu ba kumanya bakwiri kugwasa. Amagambo mashasha, kumenya bweneene, na kumenya bishasha bikugwasa kwa munsi kuguma ikiri bweneene na yoshi.',
  },
  {
    id: 'imyazi',
    name: 'imyazi.com',
    nameKifuliiru: 'imyazi.com',
    url: 'https://imyazi.com',
    description: 'A platform for Kifuliiru language resources and learning materials.',
    descriptionKifuliiru: 'Mukolwa wa Kifuliiru Language Platform. Iliri hano higulu lyo kubona abandu bitu na ngisi gundi yeshi uwangasima ukumenya bikingi ku ndeto yitu Kifuliiru.',
    detailedDescription: 'imyazi.com is a platform dedicated to Kifuliiru language resources and learning materials. It provides various tools and content to help learners understand and use the Kifuliiru language effectively. The platform focuses on practical language use, cultural context, and real-world applications of Kifuliiru in daily communication.',
    detailedDescriptionKifuliiru: 'imyazi.com iliri mukolwa wa Kifuliiru Language Platform. Iliri hano higulu lyo kubona abandu bitu na ngisi gundi yeshi uwangasima ukumenya bikingi ku ndeto yitu Kifuliiru. Mukolwa guno gutunga mikolwa ya kukoresha ndeto mu byoshi, kumenya kumenya, na kukoresha ndeto mu magambo ga munsi.',
    features: [
      'Language learning resources',
      'Cultural content',
      'Practical examples',
      'Interactive tools',
      'Community features',
      'Regular updates',
      'Multi-format content',
    ],
    featuresKifuliiru: [
      'Mikolwa ya kuyigiriza',
      'Ibindu bya kumenya',
      'Amagambo ya kukoresha',
      'Mikolwa ya kugwasa',
      'Mikolwa ya abandu ba kumanya',
      'Kugwasa ibindu bishasha',
      'Ibindu bya kumanya',
    ],
    useCases: [
      'Practical language learning',
      'Cultural understanding',
      'Daily communication practice',
      'Resource discovery',
      'Community engagement',
    ],
    useCasesKifuliiru: [
      'Kuyigiriza ndeto mu byoshi',
      'Kumenya kumenya',
      'Kukoresha ndeto mu magambo ga munsi',
      'Kubona mikolwa',
      'Kugwasa abandu ba kumanya',
    ],
    benefits: [
      'Practical focus',
      'Cultural context',
      'Real-world applications',
      'Community support',
      'Regular content updates',
    ],
    benefitsKifuliiru: [
      'Kukoresha mu byoshi',
      'Kumenya kumenya',
      'Kukoresha mu magambo ga munsi',
      'Kugwasa abandu ba kumanya',
      'Kugwasa ibindu bishasha',
    ],
    additionalInfo: 'imyazi.com emphasizes practical language use and cultural understanding, making it an ideal resource for learners who want to use Kifuliiru in real-world situations.',
    additionalInfoKifuliiru: 'imyazi.com ikusima kukoresha ndeto mu byoshi na kumenya kumenya, yibyo ikiri mukolwa muhamu higulu lyo abasoma abangasima kukoresha Kifuliiru mu magambo ga munsi.',
  },
  {
    id: 'kifuliiru-books',
    name: 'Kifuliiru Books',
    nameKifuliiru: 'Kifuliiru Books',
    url: 'https://www.kifuliiru.com/books',
    description: 'Your gateway to language learning. Discover the largest collection of Kifuliiru language books online. Free digital library featuring language learning materials, cultural literature, and educational resources for all levels.',
    descriptionKifuliiru: 'Mukolwa wa ibitaabo bya Kifuliiru. Iliri hano higulu lyo kubona ibitaabo bya Kifuliiru byoshi. Ikugwasa tumenye bingi ku ibitaabo bya Kifuliiru byoshi, ibitaabo bya kuyigiriza, ibitaabo bya kumenya, na bindi bingi.',
    detailedDescription: 'Kifuliiru Books is your gateway to language learning. It features the largest collection of Kifuliiru language books available online. The free digital library includes language learning materials, cultural literature, and educational resources suitable for all levels - from beginners to advanced learners. All books are available for free download in multiple formats, making it easy to access learning materials on any device. The collection continues to grow with new additions regularly.',
    detailedDescriptionKifuliiru: 'Kifuliiru Books iliri mukolwa wa ibitaabo bya Kifuliiru. Iliri hano higulu lyo kubona ibitaabo bya Kifuliiru byoshi. Ikugwasa tumenye bingi ku ibitaabo bya Kifuliiru byoshi, ibitaabo bya kuyigiriza, ibitaabo bya kumenya, na bindi bingi. Ibitabo byoshi biliri mahala kugura mu kumanya kumanya, yibyo bikiri vuba kubona ibitaabo kwa telefoni yoshi. Ibitabo bikugwasa kwa munsi na ibitaabo bishasha.',
    features: [
      '8+ free books available',
      'Multiple languages supported (Kifuliiru, English, French, Swahili)',
      'Language learning materials',
      'Cultural literature',
      'Educational resources',
      'Free downloads',
      'PDF and DOCX formats',
      'Mobile-friendly formats',
      'Regular new additions',
      'Categorized by topic',
      'Beginner to advanced levels',
      'Offline reading capability',
    ],
    featuresKifuliiru: [
      'Ibitabo 8+ bya mahala',
      'Zindi ndeto zingi (Kifuliiru, English, Français, Kiswahili)',
      'Ibitabo bya kuyigiriza',
      'Ibitabo bya kumenya',
      'Ibitabo bya kuyigiriza',
      'Kugura mahala',
      'PDF na DOCX',
      'Kumanya kwa telefoni',
      'Ibitabo bishasha kwa munsi',
      'Kumanya na kumanya',
      'Kuguma na abandu abayiji',
      'Kusoma kwa telefoni',
    ],
    useCases: [
      'Self-paced learning',
      'Classroom teaching materials',
      'Cultural education',
      'Reference materials',
      'Reading practice',
      'Vocabulary building',
      'Grammar study',
    ],
    useCasesKifuliiru: [
      'Kuyigiriza kwa munsi',
      'Ibitabo bya kusomesa',
      'Kuyigiriza kumenya',
      'Ibitabo bya kumenya',
      'Kusoma',
      'Kusoma amagambo',
      'Kusoma grammar',
    ],
    benefits: [
      'Completely free access',
      'Multiple format options',
      'Suitable for all levels',
      'Offline accessibility',
      'Regular content updates',
      'Multilingual support',
      'Easy to share and distribute',
    ],
    benefitsKifuliiru: [
      'Kubona mahala',
      'Kumanya kumanya',
      'Higulu lyo abasoma byoshi',
      'Kubona kwa telefoni',
      'Kugwasa ibindu bishasha',
      'Zindi ndeto zingi',
      'Vuba kugwasa na kugwasa',
    ],
    additionalInfo: 'All books in the Kifuliiru Books library are free to download and share. The platform encourages educators, students, and language enthusiasts to use these resources for learning and teaching purposes.',
    additionalInfoKifuliiru: 'Ibitabo byoshi mu Kifuliiru Books biliri mahala kugura na kugwasa. Mukolwa guno gutunga abasomesa, abasoma, na abandu abasima ndeto kukoresha mikolwa hino higulu lyo kuyigiriza na kusomesa.',
  },
  {
    id: 'kifuliiru-bookstore',
    name: 'Kifuliiru Bookstore',
    nameKifuliiru: 'Kifuliiru Bookstore',
    url: 'https://www.kifuliiru.com/bookstore',
    description: 'Preserve culture and support creators. Discover books in Kifuliiru, English, French & Swahili. Categories include medicinal herbs, language learning, stories & folktales, cultural practices, traditional foods, and children\'s books.',
    descriptionKifuliiru: 'Mukolwa wa ibitaabo bya Kifuliiru. Iliri hano higulu lyo kugura ibitaabo bya Kifuliiru. Ikugwasa tumenye bingi ku ibitaabo bya Kifuliiru, English, Français, na Kiswahili.',
    detailedDescription: 'The Kifuliiru Bookstore is dedicated to preserving culture and supporting creators. Discover a wide variety of books in Kifuliiru, English, French, and Swahili. Categories include medicinal herbs, language learning materials, stories & folktales, cultural practices, traditional foods, and children\'s books. The bookstore serves as a marketplace where authors and creators can share their work while readers can discover valuable cultural and educational content. All purchases support the creators and help preserve Kifuliiru culture.',
    detailedDescriptionKifuliiru: 'Kifuliiru Bookstore iliri mukolwa wa ibitaabo bya Kifuliiru. Iliri hano higulu lyo kugura ibitaabo bya Kifuliiru. Ikugwasa tumenye bingi ku ibitaabo bya Kifuliiru, English, Français, na Kiswahili. Mukolwa guno gutunga ibitaabo bya imiti, ibitaabo bya kuyigiriza, imigani, imikolwa ya kumenya, ibyakulya bya kera, na ibitaabo bya abaana. Mukolwa guno gutunga abandu abayandika kugwasa ibitaabo byabo na abasoma kubona ibitaabo bya kumenya na kuyigiriza. Byoshi bikugwasa abandu abayandika na kudeta kwo kumenya kwa Kifuliiru.',
    features: [
      'Books in multiple languages (Kifuliiru, English, French, Swahili)',
      'Medicinal herbs guides',
      'Language learning books',
      'Stories & folktales collection',
      'Cultural practices documentation',
      'Traditional foods recipes',
      'Children\'s books',
      'Digital and print options',
      'Creator support system',
      'Category filtering',
      'Book previews',
      'Rating and reviews',
    ],
    featuresKifuliiru: [
      'Ibitabo mu zindi ndeto zingi (Kifuliiru, English, Français, Kiswahili)',
      'Ibitabo bya imiti',
      'Ibitabo bya kuyigiriza',
      'Imigani na imigani',
      'Imikolwa ya kumenya',
      'Ibyakulya bya kera',
      'Ibitabo bya abaana',
      'Digital na print',
      'Kugwasa abandu abayandika',
      'Kuharura na kumanya',
      'Kubona ibitaabo',
      'Kumenya na kumenya',
    ],
    useCases: [
      'Supporting local authors',
      'Cultural preservation',
      'Educational resources',
      'Cultural research',
      'Family reading',
      'Language learning',
      'Heritage documentation',
    ],
    useCasesKifuliiru: [
      'Kugwasa abandu abayandika',
      'Kudeta kwo kumenya',
      'Ibitabo bya kuyigiriza',
      'Kukora kumenya',
      'Kusoma na bana',
      'Kuyigiriza ndeto',
      'Kudeta kwo kumenya',
    ],
    benefits: [
      'Supports creators and authors',
      'Preserves cultural heritage',
      'Accessible pricing',
      'Wide variety of topics',
      'Multilingual options',
      'Digital convenience',
      'Community contribution',
    ],
    benefitsKifuliiru: [
      'Kugwasa abandu abayandika',
      'Kudeta kwo kumenya',
      'Kugura vuba',
      'Kumanya kumanya',
      'Zindi ndeto zingi',
      'Kubona vuba',
      'Kugwasa abandu ba kumanya',
    ],
    additionalInfo: 'The Kifuliiru Bookstore operates on a model that prioritizes cultural preservation and creator support. A portion of proceeds goes back to supporting language preservation initiatives and helping creators continue their important work.',
    additionalInfoKifuliiru: 'Kifuliiru Bookstore ikukola higulu lyo kudeta kwo kumenya na kugwasa abandu abayandika. Bikindi bya kugura bikugwasa mikolwa ya kudeta kwo ndeto na kugwasa abandu abayandika kukola mikolwa yabo.',
  },
  {
    id: 'kifuliiru-audio',
    name: 'Kifuliiru Audio',
    nameKifuliiru: 'Kifuliiru Audio',
    url: 'https://www.kifuliiru.com/audio',
    description: 'Audio Hub - Listen to Kifuliiru stories, conversations, and cultural content. Includes numbers & counting, music & songs, stories & tales, news & radio, conversations, language lessons, and cultural content.',
    descriptionKifuliiru: 'Mukolwa wa amajwi ge\'Kifuliiru. Iliri hano higulu lyo kumwumwa amajwi ge\'Kifuliiru. Ikugwasa tumenye bingi ku amajwi ge\'Kifuliiru, imigani, amagambo, ukuharura, na bindi bingi.',
    detailedDescription: 'Kifuliiru Audio is an audio hub where you can listen to Kifuliiru stories, conversations, and cultural content. It includes numbers & counting exercises, music & songs, stories & tales, news & radio content, conversations, language lessons, and various cultural content. Perfect for improving pronunciation and listening skills. The platform features immersive mode for focused listening experiences and organizes content by categories for easy navigation. All audio content is free to access and helps learners develop authentic pronunciation and comprehension skills.',
    detailedDescriptionKifuliiru: 'Kifuliiru Audio iliri mukolwa wa amajwi ge\'Kifuliiru. Iliri hano higulu lyo kumwumwa amajwi ge\'Kifuliiru. Ikugwasa tumenye bingi ku amajwi ge\'Kifuliiru, imigani, amagambo, ukuharura, na bindi bingi. Mukolwa guno gutunga immersive mode higulu lyo kumwumwa bweneene na kumanya amajwi mu kumanya kumanya higulu lyo kubona vuba. Amajwi yoshi iliri mahala kubona na ikugwasa abasoma kumenya pronunciation na kumenya bweneene.',
    features: [
      'Numbers & counting audio (0-100, 100-200, etc.)',
      'Music & traditional songs',
      'Stories & folktales',
      'News & radio programs',
      'Conversational dialogues',
      'Language lessons',
      'Cultural content',
      'Immersive listening mode',
      'Category organization',
      'Playlist creation',
      'Download options',
      'Mobile-friendly player',
    ],
    featuresKifuliiru: [
      'Amajwi ge\'ukuharura (0-100, 100-200, na bindi)',
      'Muziki na imigani ya kera',
      'Imigani na imigani',
      'Habari na radio',
      'Amagambo',
      'Amajwi ge\'kuyigiriza',
      'Amajwi ge\'kumenya',
      'Immersive mode',
      'Kumanya na kumanya',
      'Kukola playlist',
      'Kugura',
      'Player wa telefoni',
    ],
    useCases: [
      'Pronunciation practice',
      'Listening comprehension',
      'Cultural immersion',
      'Number learning',
      'Story listening',
      'Music appreciation',
      'Conversation practice',
    ],
    useCasesKifuliiru: [
      'Kuyigiriza pronunciation',
      'Kumenya kumwumwa',
      'Kumenya kumenya',
      'Kusoma ukuharura',
      'Kumwumwa imigani',
      'Kusima muziki',
      'Kuyigiriza amagambo',
    ],
    benefits: [
      'Improves pronunciation',
      'Enhances listening skills',
      'Cultural understanding',
      'Free access to all content',
      'Mobile-friendly',
      'Offline listening capability',
      'Regular new content',
    ],
    benefitsKifuliiru: [
      'Kumenya pronunciation',
      'Kumenya kumwumwa',
      'Kumenya kumenya',
      'Kubona amajwi yoshi mahala',
      'Kubona na telefoni',
      'Kumwumwa kwa telefoni',
      'Amajwi mashasha kwa munsi',
    ],
    additionalInfo: 'Kifuliiru Audio opens content in Immersive Mode for distraction-free listening. The platform is continuously updated with new audio content including native speaker recordings, cultural performances, and educational materials.',
    additionalInfoKifuliiru: 'Kifuliiru Audio ikugwasa amajwi mu Immersive Mode higulu lyo kumwumwa bweneene. Mukolwa guno gutunga amajwi mashasha kwa munsi, kuguma na amajwi ge\'abandu abayiji ndeto, amajwi ge\'kumenya, na amajwi ge\'kuyigiriza.',
  },
];

export function getPlatformById(id: string): Platform | undefined {
  return platforms.find(p => p.id === id);
}

export function getPlatformBySlug(slug: string): Platform | undefined {
  return platforms.find(p => p.id === slug);
}

